### ISSUE TITLE
Need help with segfault (Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by serzhiio** [serde-rs/serde#1729]
Could someone help with this, what could be a source of error:
```
Segmentation fault (core dumped)
#0  tcache_get (tc_idx=2) at malloc.c:2934
#1  __GI___libc_malloc (bytes=48) at malloc.c:3042
#2  0x0000561e6022d2f9 in <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq
    ()
#3  0x0000561e602084d7 in <serde::private::de::content::ContentRefDeserializer<E> as serde::de::Deserializer>::deserialize_seq ()
#4  0x0000561e6021af2d in <serde::private::de::content::ContentRefDeserializer<E> as serde::de::Deserializer>::deserialize_struct ()
#5  0x0000561e602360ab in deribit::parse::response::_IMPL_DESERIALIZE_FOR_PublicData::<impl serde::de::Deserialize for deribit::parse::response::PublicData>::deserialize ()
#6  0x0000561e60206679 in <serde::private::de::content::ContentRefDeserializer<E> as serde::de::Deserializer>::deserialize_any ()
#7  0x0000561e60235bb9 in deribit::parse::response::_IMPL_DESERIALIZE_FOR_Params::<impl serde::de::Deserialize for deribit::parse::response::Params<Stream>>::deserialize ()
#8  0x0000561e60202eb2 in <serde::private::de::content::ContentRefDeserializer<E> as serde::de::Deserializer>::deserialize_any ()
#9  0x0000561e602347e9 in deribit::parse::response::_IMPL_DESERIALIZE_FOR_WSResponse::<impl serde::de::Deserialize for deribit::parse::response::WSResponse<Request,Stream>>::deserialize ()
#10 0x0000561e601e649c in serde_json::de::from_str ()
#11 0x0000561e601cd973 in <deribit::Deribit as models::exchange::traits::ExchangeEvents>::on_public_data ()
#12 0x0000561e60168317 in <models::exchange::channel_agent::TriChannelAgent as models::exchange::traits::channels::ChannelAgent>::subscribe::{{closure}} ()
#13 0x0000561e60188bc6 in models::helpers::connectors::websocket::websocket::{{closure}} ()
#14 0x0000561e6019863e in <std::future::GenFuture<T> as core::future::future::Future>::poll ()
#15 0x0000561e6019d0c0 in <std::future::GenFuture<T> as core::future::future::Future>::poll ()
#16 0x0000561e601b3041 in async_task::raw::RawTask<F,R,S,T>::run ()
#17 0x0000561e60316daf in std::thread::local::LocalKey<T>::with ()
#18 0x0000561e6030ff40 in async_std::task::executor::pool::main_loop ()
```

**Comment by serzhiio** [comment]
a bit more detailed backtrace:
`(gdb) bt
#0  tcache_get (tc_idx=2) at malloc.c:2934
#1  __GI___libc_malloc (bytes=48) at malloc.c:3042
#2  0x0000556ed59c845f in std::sys::unix::alloc::<impl core::alloc::GlobalAlloc for std::alloc::System>::alloc () at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7//src/libstd/sys/unix/alloc.rs:14
#3  __rdl_alloc () at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7//src/libstd/alloc.rs:236
#4  alloc::alloc::alloc (layout=...) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/liballoc/alloc.rs:81
#5  <alloc::alloc::Global as core::alloc::AllocRef>::alloc (self=<optimized out>, layout=...) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/liballoc/alloc.rs:169
#6  alloc::raw_vec::RawVec<T,A>::allocate_in (capacity=2, zeroed=false, a=...) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/liballoc/raw_vec.rs:88
#7  alloc::raw_vec::RawVec<T>::with_capacity (capacity=2) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/liballoc/raw_vec.rs:140
#8  alloc::vec::Vec<T>::with_capacity (capacity=2) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/liballoc/vec.rs:355
#9  <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq (seq=<optimized out>, self=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/impls.rs:864
#10 serde::private::de::content::visit_content_seq_ref (content=..., visitor=...) at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/private/de.rs:1762
#11 <serde::private::de::content::ContentRefDeserializer<E> as serde::de::Deserializer>::deserialize_seq (self=..., visitor=...) at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/private/de.rs:2021
#12 0x0000556ed59f06ac in deribit::parse::response::_IMPL_DESERIALIZE_FOR_Params::<impl serde::de::Deserialize for deribit::parse::response::Params<Stream>>::deserialize (__deserializer=...)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/impls.rs:877
#13 0x0000556ed59e5219 in deribit::parse::response::_IMPL_DESERIALIZE_FOR_WSResponse::<impl serde::de::Deserialize for deribit::parse::response::WSResponse<Request,Stream>>::deserialize (__deserializer=<optimized out>)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104/src/de/mod.rs:786
#14 0x0000556ed59f3eba in <deribit::Deribit as models::exchange::traits::ExchangeEvents>::on_public_data (self=0x556ed6ed7d40, data=..., channel=0x556ed6ed7eb8)
    at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.45/src/de.rs:2177
#15 0x0000556ed5950d80 in <models::exchange::channel_agent::TriChannelAgent as models::exchange::traits::channels::ChannelAgent>::subscribe::{{closure}} (data=...)
    at /home/debian/capitalist_bot_v7/models/src/exchange/channel_agent.rs:284
#16 0x0000556ed594f392 in models::helpers::connectors::websocket::websocket::{{closure}} () at /home/debian/capitalist_bot_v7/models/src/helpers/connectors/websocket.rs:141
#17 0x0000556ed594c7c5 in <std::future::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=0x7ffa60090aa0) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/future.rs:43
#18 0x0000556ed5913a1b in <core::pin::Pin<P> as core::future::future::Future>::poll (self=..., cx=0x7ffa6e3ca7a8) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libcore/future/future.rs:119
#19 std::future::poll_with_tls_context (f=...) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/future.rs:98
#20 <models::exchange::channel_agent::TriChannelAgent as models::exchange::traits::channels::ChannelAgent>::subscribe::{{closure}} () at /home/debian/capitalist_bot_v7/models/src/exchange/channel_agent.rs:296
#21 <std::future::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=0x7ffa6e3ca7a8) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/future.rs:43
#22 std::future::poll_with_tls_context (f=...) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/future.rs:98
#23 async_std::task::builder::Builder::spawn::{{closure}} () at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/task/builder.rs:64
#24 <std::future::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=0x7ffa6e3ca7a8) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/future.rs:43
#25 async_task::raw::RawTask<F,R,S,T>::run (ptr=0x556ed6ed3170) at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-1.3.0/src/raw.rs:505
#26 0x0000556ed58e2a1e in async_task::task::Task<T>::run (self=...) at /home/debian/.cargo/registry/src/github.com-1ecc6299db9ec823/async-task-1.3.0/src/task.rs:239
#27 async_std::task::builder::Runnable::run::{{closure}}::{{closure}} () at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/task/builder.rs:81
#28 async_std::utils::abort_on_panic (f=...) at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/utils.rs:16
#29 async_std::task::builder::Runnable::run::{{closure}} () at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/task/builder.rs:81
#30 async_std::task::task::Task::set_current::{{closure}} (current=<optimized out>) at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/task/task.rs:129
#31 std::thread::local::LocalKey<T>::try_with (self=<optimized out>, f=...) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/thread/local.rs:262
#32 std::thread::local::LocalKey<T>::with (f=..., self=<optimized out>) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/thread/local.rs:239
#33 async_std::task::task::Task::set_current (task=<optimized out>, f=...) at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/task/task.rs:124
#34 async_std::task::builder::Runnable::run (self=...) at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/task/builder.rs:81
#35 async_std::task::executor::pool::main_loop () at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/task/executor/pool.rs:114
#36 core::ops::function::FnOnce::call_once () at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libcore/ops/function.rs:232
#37 async_std::utils::abort_on_panic (f=<optimized out>) at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/utils.rs:16
#38 async_std::task::executor::pool::POOL::{{closure}}::{{closure}} () at /home/debian/.cargo/git/checkouts/async-std-2413e748fca81ce4/1d87583/src/task/executor/pool.rs:46
--Type <RET> for more, q to quit, c to continue without paging--
#39 std::sys_common::backtrace::__rust_begin_short_backtrace (f=...) at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/sys_common/backtrace.rs:129
#40 0x0000556ed58eb97b in core::ops::function::FnOnce::call_once{{vtable-shim}} () at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/libstd/thread/mod.rs:475
#41 0x0000556ed5acea9f in <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once () at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/liballoc/boxed.rs:1015
#42 0x0000556ed5ad005c in std::sys::unix::thread::Thread::new::thread_start () at /rustc/3761dcd3467441f78939ccb3b341b03b6a7558d7/src/liballoc/boxed.rs:1015
#43 0x00007ffa6e736fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#44 0x00007ffa6e64d4cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95`

**Comment by serzhiio** [comment]
Closing, bc its likely a memory allocating issue and not a serde fault.
