### ISSUE TITLE
panicked at 'internal error: entered unreachable code' when returning f64 query msg

### ISSUE THREAD

**Issue by LCyson** [serde-rs/serde#2154]
Hi there, I keep meeting this bug when I try to return a query msg that contains a f64 field:
```
thread 'tests::tests::proper_get_multiplier' panicked at 'internal error: entered unreachable code', /Users/xingchen/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-json-wasm-0.3.2/src/ser/mod.rs:232:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:50:5
   3: <&mut serde_json_wasm::ser::Serializer as serde::ser::Serializer>::serialize_f64
             at /Users/xingchen/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-json-wasm-0.3.2/src/ser/mod.rs:232:9
   4: serde::ser::impls::<impl serde::ser::Serialize for f64>::serialize
             at /Users/xingchen/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.133/src/ser/impls.rs:15:17
   5: <serde_json_wasm::ser::struct_::SerializeStruct as serde::ser::SerializeStruct>::serialize_field
             at /Users/xingchen/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-json-wasm-0.3.2/src/ser/struct_.rs:34:9
   6: passport::msg::_::<impl serde::ser::Serialize for passport::msg::MultiplierResponse>::serialize
             at ./src/msg.rs:35:10
   7: serde_json_wasm::ser::to_vec
             at /Users/xingchen/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-json-wasm-0.3.2/src/ser/mod.rs:449:5
   8: cosmwasm_std::serde::to_vec
             at /Users/xingchen/.cargo/registry/src/github.com-1ecc6299db9ec823/cosmwasm-std-0.16.3/src/serde.rs:23:5
   9: cosmwasm_std::serde::to_binary
             at /Users/xingchen/.cargo/registry/src/github.com-1ecc6299db9ec823/cosmwasm-std-0.16.3/src/serde.rs:30:5
  10: passport::contract::query
             at ./src/contract.rs:42:47
  11: passport::tests::tests::proper_get_multiplier
             at ./src/tests.rs:62:19
  12: passport::tests::tests::proper_get_multiplier::{{closure}}
             at ./src/tests.rs:34:5
  13: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
  14: core::ops::function::FnOnce::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
```

it happens there:
```
...
        QueryMsg::GetMultiplier { scores } => to_binary(&query_multiplier(scores)?),
...
pub fn query_multiplier(scores: String) -> StdResult<MultiplierResponse> ...
...
```

Can anyone suggest help to work around with this issue? Thanks in advance!

**Comment by avitex** [comment]
This is not relevant to this project :)

The assertion is made here: https://github.com/CosmWasm/serde-json-wasm/blob/main/src/ser/mod.rs#L231
As such, this is the relevant project you should ask the question of: https://github.com/CosmWasm/serde-json-wasm
