### ISSUE TITLE
Regression of correctness on `armv7-unknown-linux-gnueabihf` (`v1.0.160` => `v1.0.164`)

### ISSUE THREAD

**Issue by kdy1** [serde-rs/serde#2477]
It seems like `serde` has a regression of correctness within range of `v1.0.160` to `v1.0.164`

 - `v1.0.160`: CI passes. https://github.com/swc-project/swc/pull/7533
 - `v1.0.164`: CI fails. https://github.com/swc-project/swc/pull/7524

The failure is about deserializing a json string to `swc_ecma_ast::Program`, and the error message says 

```

  ● works with visitor

    failed to deserialize Program

    Caused by:
        invalid type: floating point `0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000073879405460019`, expected field identifier

      239 |                 return this.transformSync(plugin(m), newOptions);
      240 |             }
    > 241 |             return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
          |                             ^
      242 |         }
      243 |         else if (fallbackBindings) {
      244 |             if (plugin && !this.fallbackBindingsPluginWarningDisplayed) {

      at Compiler.transformSync (../index.js:241:29)
      at Compiler.transformSync (../index.js:239:29)
      at Object.transformSync (../index.js:348:21)
      at Object.<anonymous> (__tests__/transform/plugin_test.js:107:9)


```

**Comment by oli-obk** [comment]
Can you create a minimization of your issue?

**Comment by kdy1** [comment]
I can try, but I'm not sure if it's possible. It requires running some rust code from `armv7-unknown-linux-gnueabihf`, and I'm not sure what's the problematic code.

**Comment by dtolnay** [comment]
I don't think this is gonna be actionable on our end without a minimization, and hopefully a bisect.
